{% set name = "pycox" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c209c6b24d9262db7b8edb9a886b1a3bb73c9d6db9fb4559b5fb994e30743d6f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - feather-format >=0.4.0
    - h5py >=2.9.0
    - numba >=0.44
    - py7zr >=0.11.3
    - python >=3.6
    - requests >=2.22.0
    - scikit-learn >=0.21.2
    - torchtuples >=0.2.0

test:
  imports:
    - pycox
    - pycox.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/havakv/pycox
  summary: Survival analysis with PyTorch
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
